---
name: CMake
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            cmake_build_type: RelOnHost

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/bld

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/bld
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.cmake_build_type}}

    - name: Build
      working-directory: ${{runner.workspace}}/bld
      shell: bash
      run: cmake --build . --config ${{matrix.cmake_build_type}}
